#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters:
name=FISHEARS
trgt=$1
if [ -z "$trgt" ]
then
  echo "No version specified"
  exit
fi
if [ "$trgt" = "42" ]
then
echo 'Building for Android 4.2'
fldr="datadrive"
else
echo 'Building for Android 4.1'
fldr="developer"
fi
finalout=~/$fldr/android/system/out/target/product/galaxysmtd
androidtop=~/$fldr/android/system
secsign=~/$fldr/android/system/build/target/product/security

#****************************************************************
## Clean build environment:
cd ~/$fldr/android/system
make installclean
rm $finalout/boot.img

#****************************************************************
## Set kernel version in init:
cd ~/$fldr/android/system/kernel/samsung/aries
#git checkout jellybean
export LOCALVERSION="-FISHEARS"

#****************************************************************
## Build the kernel:
cd ~/$fldr/android/system/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
