#!/bin/sh
#Script to push FISHEARS repo changes
#****************************************************************
## Set basic parameters:
trgt=$1
if [ -z "$trgt" ]
then
  echo "No version specified"
  exit
fi
if [ "$trgt" = "42" ]
then
echo 'Pushing commits for Android 4.2'
fldr="datadrive"
br="cm-10.1"
else
echo 'Pushing commits for Android 4.1'
fldr="developer"
br="jellybean"
fi
#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## push my changes:

echo 'scripts'
cd ~/datadrive/scripts/
git push origin master

echo 'recovery'
cd ~/$fldr/android/system/bootable/recovery/
git push origin $br

echo 'build'
cd ~/$fldr/android/system/build/
git push origin $br

echo 'hardware'
cd ~/$fldr/android/system/hardware/samsung/
git push origin $br

echo 'aries-common'
cd ~/$fldr/android/system/device/samsung/aries-common/
git push origin $br

echo 'galaxysmtd'
cd ~/$fldr/android/system/device/samsung/galaxysmtd/
git push origin $br

echo 'base'
cd ~/$fldr/android/system/frameworks/base/
git push origin $br

echo 'kernel'
cd ~/$fldr/android/system/kernel/samsung/aries/
git push origin $br

echo 'settings'
cd ~/$fldr/android/system/packages/apps/Settings/
git push origin $br

echo 'cm'
cd ~/$fldr/android/system/vendor/cm/
git push origin $br

#****************************************************************
## FOR 4.1 ONLY
if [ "$trgt" = "cm" ]
then

echo 'android'
cd ~/$fldr/android/system/android/
git push origin $br

echo 'servicemode'
cd ~/$fldr/android/system/packages/apps/SamsungServiceMode/
git push origin $br
fi

#****************************************************************
## FOR 4.2 ONLY
if [ "$trgt" = "42" ]
then

echo 'camera'
cd ~/$fldr/android/system/packages/apps/Camera/
git push origin $br

echo 'phone'
cd ~/$fldr/android/system/packages/apps/Phone/
git push origin $br

echo 'device-common'
cd ~/$fldr/android/system/device/common/
git push origin $br

echo 'vold'
cd ~/$fldr/android/system/system/vold/
git push origin $br

echo 'telephony'
cd ~/$fldr/android/system/frameworks/opt/telephony/
git push origin $br
fi
#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC

cd ~/$fldr/android/system/